// Code generated by dagger. DO NOT EDIT.

package dagger

import (
	"context"
	"encoding/json"

	"github.com/dagger/querybuilder"
)

// Retrieve the binding value, as type Helm
func (r *Binding) AsHelm() *Helm { // helm (https://github.com/disaster37/dagger-library-go/tree/b753e824a9c4beec16d624fb1b7f59b073934c78/helm/main.go#L29)
	q := r.query.Select("asHelm")

	return &Helm{
		query: q,
	}
}

// Create or update a binding of type Helm in the environment
func (r *Env) WithHelmInput(name string, value *Helm, description string) *Env { // helm (https://github.com/disaster37/dagger-library-go/tree/b753e824a9c4beec16d624fb1b7f59b073934c78/helm/main.go#L29)
	assertNotNil("value", value)
	q := r.query.Select("withHelmInput")
	q = q.Arg("name", name)
	q = q.Arg("value", value)
	q = q.Arg("description", description)

	return &Env{
		query: q,
	}
}

// Declare a desired Helm output to be assigned in the environment
func (r *Env) WithHelmOutput(name string, description string) *Env { // helm (https://github.com/disaster37/dagger-library-go/tree/b753e824a9c4beec16d624fb1b7f59b073934c78/helm/main.go#L29)
	q := r.query.Select("withHelmOutput")
	q = q.Arg("name", name)
	q = q.Arg("description", description)

	return &Env{
		query: q,
	}
}

type Helm struct { // helm (https://github.com/disaster37/dagger-library-go/tree/b753e824a9c4beec16d624fb1b7f59b073934c78/helm/main.go#L29)
	query *querybuilder.Selection

	id   *ID
	lint *string
}
type WithHelmFunc func(r *Helm) *Helm

// With calls the provided function with current Helm.
//
// This is useful for reusability and readability by not breaking the calling chain.
func (r *Helm) With(f WithHelmFunc) *Helm {
	return f(r)
}

func (r *Helm) WithGraphQLQuery(q *querybuilder.Selection) *Helm {
	return &Helm{
		query: q,
	}
}

// HelmCiOpts contains options for Helm.Ci
type HelmCiOpts struct {
	//
	// The registry
	// You need to provide it if run from CI
	//
	Registry string // helm (https://github.com/disaster37/dagger-library-go/tree/b753e824a9c4beec16d624fb1b7f59b073934c78/helm/pipeline.go#L26)
	//
	// The repository inside the registry
	// You need to provide it if run from CI
	//
	Repository string // helm (https://github.com/disaster37/dagger-library-go/tree/b753e824a9c4beec16d624fb1b7f59b073934c78/helm/pipeline.go#L31)
	//
	// The helm paths
	//
	//
	// Default: ["."]
	HelmPaths []string // helm (https://github.com/disaster37/dagger-library-go/tree/b753e824a9c4beec16d624fb1b7f59b073934c78/helm/pipeline.go#L36)
	//
	// If you are on CI, provide the CI type to set the right stuff when commit to ovoid loop for ever
	//
	Ci string // helm (https://github.com/disaster37/dagger-library-go/tree/b753e824a9c4beec16d624fb1b7f59b073934c78/helm/pipeline.go#L40)
	//
	// The image version to publish
	// You need to provide it if run from CI
	//
	Version string // helm (https://github.com/disaster37/dagger-library-go/tree/b753e824a9c4beec16d624fb1b7f59b073934c78/helm/pipeline.go#L45)
	//
	// The registry username
	// You need to provide it if run from CI
	//
	RegistryUsername *Secret // helm (https://github.com/disaster37/dagger-library-go/tree/b753e824a9c4beec16d624fb1b7f59b073934c78/helm/pipeline.go#L50)
	//
	// The registry password
	// You need to provide it if run from CI
	//
	RegistryPassword *Secret // helm (https://github.com/disaster37/dagger-library-go/tree/b753e824a9c4beec16d624fb1b7f59b073934c78/helm/pipeline.go#L55)
	//
	// The git token
	// You need to provide it if run from CI
	//
	GitToken *Secret // helm (https://github.com/disaster37/dagger-library-go/tree/b753e824a9c4beec16d624fb1b7f59b073934c78/helm/pipeline.go#L60)
	//
	// The git repo URL
	// You need to provide it when you are on PullRequest
	//
	GitRepoURL string // helm (https://github.com/disaster37/dagger-library-go/tree/b753e824a9c4beec16d624fb1b7f59b073934c78/helm/pipeline.go#L65)
	//
	// The git branch where you should to push
	// You need to provide it when you are on PullRequest or on Tag
	//
	GitBranch string // helm (https://github.com/disaster37/dagger-library-go/tree/b753e824a9c4beec16d624fb1b7f59b073934c78/helm/pipeline.go#L70)
	//
	// Dry-run: skip push and git commit/push even when --ci is set.
	//
	DryRun bool // helm (https://github.com/disaster37/dagger-library-go/tree/b753e824a9c4beec16d624fb1b7f59b073934c78/helm/pipeline.go#L74)
}

func (r *Helm) Ci(opts ...HelmCiOpts) *Directory { // helm (https://github.com/disaster37/dagger-library-go/tree/b753e824a9c4beec16d624fb1b7f59b073934c78/helm/pipeline.go#L20)
	q := r.query.Select("ci")
	for i := len(opts) - 1; i >= 0; i-- {
		// `registry` optional argument
		if !querybuilder.IsZeroValue(opts[i].Registry) {
			q = q.Arg("registry", opts[i].Registry)
		}
		// `repository` optional argument
		if !querybuilder.IsZeroValue(opts[i].Repository) {
			q = q.Arg("repository", opts[i].Repository)
		}
		// `helmPaths` optional argument
		if !querybuilder.IsZeroValue(opts[i].HelmPaths) {
			q = q.Arg("helmPaths", opts[i].HelmPaths)
		}
		// `ci` optional argument
		if !querybuilder.IsZeroValue(opts[i].Ci) {
			q = q.Arg("ci", opts[i].Ci)
		}
		// `version` optional argument
		if !querybuilder.IsZeroValue(opts[i].Version) {
			q = q.Arg("version", opts[i].Version)
		}
		// `registryUsername` optional argument
		if !querybuilder.IsZeroValue(opts[i].RegistryUsername) {
			q = q.Arg("registryUsername", opts[i].RegistryUsername)
		}
		// `registryPassword` optional argument
		if !querybuilder.IsZeroValue(opts[i].RegistryPassword) {
			q = q.Arg("registryPassword", opts[i].RegistryPassword)
		}
		// `gitToken` optional argument
		if !querybuilder.IsZeroValue(opts[i].GitToken) {
			q = q.Arg("gitToken", opts[i].GitToken)
		}
		// `gitRepoUrl` optional argument
		if !querybuilder.IsZeroValue(opts[i].GitRepoURL) {
			q = q.Arg("gitRepoUrl", opts[i].GitRepoURL)
		}
		// `gitBranch` optional argument
		if !querybuilder.IsZeroValue(opts[i].GitBranch) {
			q = q.Arg("gitBranch", opts[i].GitBranch)
		}
		// `dryRun` optional argument
		if !querybuilder.IsZeroValue(opts[i].DryRun) {
			q = q.Arg("dryRun", opts[i].DryRun)
		}
	}

	return &Directory{
		query: q,
	}
}

// HelmGenerateCiOpts contains options for Helm.GenerateCi
type HelmGenerateCiOpts struct {
	//
	// Branches that trigger the pipeline
	//
	//
	// Default: ["main"]
	Branches []string // helm (https://github.com/disaster37/dagger-library-go/tree/b753e824a9c4beec16d624fb1b7f59b073934c78/helm/pipeline.go#L251)
	//
	// Helm chart directory paths
	//
	//
	// Default: ["."]
	HelmPaths []string // helm (https://github.com/disaster37/dagger-library-go/tree/b753e824a9c4beec16d624fb1b7f59b073934c78/helm/pipeline.go#L256)
	//
	// Dagger CLI version to use in CI (empty = engine default)
	//
	DaggerVersion string // helm (https://github.com/disaster37/dagger-library-go/tree/b753e824a9c4beec16d624fb1b7f59b073934c78/helm/pipeline.go#L260)
	//
	// OCI registry URL. Empty = renderer default (ghcr.io on GitHub).
	//
	Registry string // helm (https://github.com/disaster37/dagger-library-go/tree/b753e824a9c4beec16d624fb1b7f59b073934c78/helm/pipeline.go#L264)
	//
	// Repository path inside the registry.
	//
	Repository string // helm (https://github.com/disaster37/dagger-library-go/tree/b753e824a9c4beec16d624fb1b7f59b073934c78/helm/pipeline.go#L268)
	//
	// Branch commits land here when running on a tag.
	//
	//
	// Default: "main"
	DefaultBranch string // helm (https://github.com/disaster37/dagger-library-go/tree/b753e824a9c4beec16d624fb1b7f59b073934c78/helm/pipeline.go#L273)
	//
	// Configurable dagger module reference.
	// Defaults to this module's current version (auto-detected).
	//
	ModuleRef string // helm (https://github.com/disaster37/dagger-library-go/tree/b753e824a9c4beec16d624fb1b7f59b073934c78/helm/pipeline.go#L278)
	//
	// GitHub: secret name for registry username (empty = github.actor).
	//
	RegistryUsernameKey string // helm (https://github.com/disaster37/dagger-library-go/tree/b753e824a9c4beec16d624fb1b7f59b073934c78/helm/pipeline.go#L282)
	//
	// GitHub: secret name for registry password (empty = GITHUB_TOKEN).
	//
	RegistryPasswordKey string // helm (https://github.com/disaster37/dagger-library-go/tree/b753e824a9c4beec16d624fb1b7f59b073934c78/helm/pipeline.go#L286)
	//
	// Jenkins: credential id for registry username/password.
	//
	RegistryCredential string // helm (https://github.com/disaster37/dagger-library-go/tree/b753e824a9c4beec16d624fb1b7f59b073934c78/helm/pipeline.go#L290)
	//
	// Jenkins: credential id for git token.
	//
	GitTokenCredential string // helm (https://github.com/disaster37/dagger-library-go/tree/b753e824a9c4beec16d624fb1b7f59b073934c78/helm/pipeline.go#L294)
	//
	// GitLab: CI/CD variable name for registry username.
	//
	RegistryUsernameVar string // helm (https://github.com/disaster37/dagger-library-go/tree/b753e824a9c4beec16d624fb1b7f59b073934c78/helm/pipeline.go#L298)
	//
	// GitLab: CI/CD variable name for registry password.
	//
	RegistryPasswordVar string // helm (https://github.com/disaster37/dagger-library-go/tree/b753e824a9c4beec16d624fb1b7f59b073934c78/helm/pipeline.go#L302)
	//
	// GitLab: CI/CD variable name for git token.
	//
	GitTokenVar string // helm (https://github.com/disaster37/dagger-library-go/tree/b753e824a9c4beec16d624fb1b7f59b073934c78/helm/pipeline.go#L306)
}

// GenerateCi generates CI pipeline files for the given CI system.
func (r *Helm) GenerateCi(ci string, opts ...HelmGenerateCiOpts) *Directory { // helm (https://github.com/disaster37/dagger-library-go/tree/b753e824a9c4beec16d624fb1b7f59b073934c78/helm/pipeline.go#L241)
	q := r.query.Select("generateCi")
	for i := len(opts) - 1; i >= 0; i-- {
		// `branches` optional argument
		if !querybuilder.IsZeroValue(opts[i].Branches) {
			q = q.Arg("branches", opts[i].Branches)
		}
		// `helmPaths` optional argument
		if !querybuilder.IsZeroValue(opts[i].HelmPaths) {
			q = q.Arg("helmPaths", opts[i].HelmPaths)
		}
		// `daggerVersion` optional argument
		if !querybuilder.IsZeroValue(opts[i].DaggerVersion) {
			q = q.Arg("daggerVersion", opts[i].DaggerVersion)
		}
		// `registry` optional argument
		if !querybuilder.IsZeroValue(opts[i].Registry) {
			q = q.Arg("registry", opts[i].Registry)
		}
		// `repository` optional argument
		if !querybuilder.IsZeroValue(opts[i].Repository) {
			q = q.Arg("repository", opts[i].Repository)
		}
		// `defaultBranch` optional argument
		if !querybuilder.IsZeroValue(opts[i].DefaultBranch) {
			q = q.Arg("defaultBranch", opts[i].DefaultBranch)
		}
		// `moduleRef` optional argument
		if !querybuilder.IsZeroValue(opts[i].ModuleRef) {
			q = q.Arg("moduleRef", opts[i].ModuleRef)
		}
		// `registryUsernameKey` optional argument
		if !querybuilder.IsZeroValue(opts[i].RegistryUsernameKey) {
			q = q.Arg("registryUsernameKey", opts[i].RegistryUsernameKey)
		}
		// `registryPasswordKey` optional argument
		if !querybuilder.IsZeroValue(opts[i].RegistryPasswordKey) {
			q = q.Arg("registryPasswordKey", opts[i].RegistryPasswordKey)
		}
		// `registryCredential` optional argument
		if !querybuilder.IsZeroValue(opts[i].RegistryCredential) {
			q = q.Arg("registryCredential", opts[i].RegistryCredential)
		}
		// `gitTokenCredential` optional argument
		if !querybuilder.IsZeroValue(opts[i].GitTokenCredential) {
			q = q.Arg("gitTokenCredential", opts[i].GitTokenCredential)
		}
		// `registryUsernameVar` optional argument
		if !querybuilder.IsZeroValue(opts[i].RegistryUsernameVar) {
			q = q.Arg("registryUsernameVar", opts[i].RegistryUsernameVar)
		}
		// `registryPasswordVar` optional argument
		if !querybuilder.IsZeroValue(opts[i].RegistryPasswordVar) {
			q = q.Arg("registryPasswordVar", opts[i].RegistryPasswordVar)
		}
		// `gitTokenVar` optional argument
		if !querybuilder.IsZeroValue(opts[i].GitTokenVar) {
			q = q.Arg("gitTokenVar", opts[i].GitTokenVar)
		}
	}
	q = q.Arg("ci", ci)

	return &Directory{
		query: q,
	}
}

// HelmGenerateDocumentationOpts contains options for Helm.GenerateDocumentation
type HelmGenerateDocumentationOpts struct {
	//
	// The target file
	//
	//
	// Default: "README.md"
	TargetFile string // helm (https://github.com/disaster37/dagger-library-go/tree/b753e824a9c4beec16d624fb1b7f59b073934c78/helm/generate_doc.go#L16)
	//
	// Config file for readme-generator
	//
	ConfigFile string // helm (https://github.com/disaster37/dagger-library-go/tree/b753e824a9c4beec16d624fb1b7f59b073934c78/helm/generate_doc.go#L20)
}

// GenerateDocumentation permit to generate helm documentation
// It will return the readme file
func (r *Helm) GenerateDocumentation(opts ...HelmGenerateDocumentationOpts) *File { // helm (https://github.com/disaster37/dagger-library-go/tree/b753e824a9c4beec16d624fb1b7f59b073934c78/helm/generate_doc.go#L11)
	q := r.query.Select("generateDocumentation")
	for i := len(opts) - 1; i >= 0; i-- {
		// `targetFile` optional argument
		if !querybuilder.IsZeroValue(opts[i].TargetFile) {
			q = q.Arg("targetFile", opts[i].TargetFile)
		}
		// `configFile` optional argument
		if !querybuilder.IsZeroValue(opts[i].ConfigFile) {
			q = q.Arg("configFile", opts[i].ConfigFile)
		}
	}

	return &File{
		query: q,
	}
}

// HelmGenerateSchemaOpts contains options for Helm.GenerateSchema
type HelmGenerateSchemaOpts struct {
	//
	// The target file
	//
	//
	// Default: "values.schema.json"
	TargetFile string // helm (https://github.com/disaster37/dagger-library-go/tree/b753e824a9c4beec16d624fb1b7f59b073934c78/helm/generate_schema.go#L16)
	//
	// Config file for readme-generator
	//
	ConfigFile string // helm (https://github.com/disaster37/dagger-library-go/tree/b753e824a9c4beec16d624fb1b7f59b073934c78/helm/generate_schema.go#L20)
}

// GenerateSchema permit to generate helm schema
// It will return the values.schema.json file
func (r *Helm) GenerateSchema(opts ...HelmGenerateSchemaOpts) *File { // helm (https://github.com/disaster37/dagger-library-go/tree/b753e824a9c4beec16d624fb1b7f59b073934c78/helm/generate_schema.go#L11)
	q := r.query.Select("generateSchema")
	for i := len(opts) - 1; i >= 0; i-- {
		// `targetFile` optional argument
		if !querybuilder.IsZeroValue(opts[i].TargetFile) {
			q = q.Arg("targetFile", opts[i].TargetFile)
		}
		// `configFile` optional argument
		if !querybuilder.IsZeroValue(opts[i].ConfigFile) {
			q = q.Arg("configFile", opts[i].ConfigFile)
		}
	}

	return &File{
		query: q,
	}
}

func (r *Helm) GeneratorContainer() *Container { // helm (https://github.com/disaster37/dagger-library-go/tree/b753e824a9c4beec16d624fb1b7f59b073934c78/helm/main.go#L33)
	q := r.query.Select("generatorContainer")

	return &Container{
		query: q,
	}
}

func (r *Helm) HelmContainer() *Container { // helm (https://github.com/disaster37/dagger-library-go/tree/b753e824a9c4beec16d624fb1b7f59b073934c78/helm/main.go#L32)
	q := r.query.Select("helmContainer")

	return &Container{
		query: q,
	}
}

// A unique identifier for this Helm.
func (r *Helm) ID(ctx context.Context) (ID, error) {
	if r.id != nil {
		return *r.id, nil
	}
	q := r.query.Select("id")

	var response ID

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

// XXX_GraphQLType is an internal function. It returns the native GraphQL type name
func (r *Helm) XXX_GraphQLType() string {
	return "Helm"
}

// XXX_GraphQLIDType is an internal function. It returns the native GraphQL type name for the ID of this object
func (r *Helm) XXX_GraphQLIDType() string {
	return "ID"
}

// XXX_GraphQLID is an internal function. It returns the underlying type ID
func (r *Helm) XXX_GraphQLID(ctx context.Context) (string, error) {
	id, err := r.ID(ctx)
	if err != nil {
		return "", err
	}
	return string(id), nil
}

func (r *Helm) MarshalJSON() ([]byte, error) {
	id, err := r.ID(marshalCtx)
	if err != nil {
		return nil, err
	}
	return json.Marshal(id)
}
func (r *Helm) UnmarshalJSON(bs []byte) error {
	var id string
	err := json.Unmarshal(bs, &id)
	if err != nil {
		return err
	}
	*r = Helm{query: selectNode(dag.query, id, "Helm")}
	return nil
}

// Lint permit to lint helm chart
func (r *Helm) Lint(ctx context.Context) (string, error) { // helm (https://github.com/disaster37/dagger-library-go/tree/b753e824a9c4beec16d624fb1b7f59b073934c78/helm/lint.go#L10)
	if r.lint != nil {
		return *r.lint, nil
	}
	q := r.query.Select("lint")

	var response string

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

// HelmMigrateValuesTagsOpts contains options for Helm.MigrateValuesTags
type HelmMigrateValuesTagsOpts struct {
	//
	// The values file to migrate
	//
	//
	// Default: "values.yaml"
	ValuesFile string // helm (https://github.com/disaster37/dagger-library-go/tree/b753e824a9c4beec16d624fb1b7f59b073934c78/helm/migrate.go#L22)
	//
	// Config file for readme-generator
	//
	ConfigFile string // helm (https://github.com/disaster37/dagger-library-go/tree/b753e824a9c4beec16d624fb1b7f59b073934c78/helm/migrate.go#L26)
	//
	// Output file path. If empty, valuesFile is rewritten in place.
	//
	OutputFile string // helm (https://github.com/disaster37/dagger-library-go/tree/b753e824a9c4beec16d624fb1b7f59b073934c78/helm/migrate.go#L30)
}

// MigrateValuesTags permit to migrate values.yaml metadata tags
// It rewrites old concrete array indices ([0], [1]) in @param / @skip / @extra
// metadata comment paths to the new generic [] syntax used by the Go
// readme-generator-for-helm fork. The operation is idempotent and only modifies
// metadata comment lines; YAML values, modifiers, and descriptions are preserved.
// It returns the migrated values file.
func (r *Helm) MigrateValuesTags(opts ...HelmMigrateValuesTagsOpts) *File { // helm (https://github.com/disaster37/dagger-library-go/tree/b753e824a9c4beec16d624fb1b7f59b073934c78/helm/migrate.go#L16)
	q := r.query.Select("migrateValuesTags")
	for i := len(opts) - 1; i >= 0; i-- {
		// `valuesFile` optional argument
		if !querybuilder.IsZeroValue(opts[i].ValuesFile) {
			q = q.Arg("valuesFile", opts[i].ValuesFile)
		}
		// `configFile` optional argument
		if !querybuilder.IsZeroValue(opts[i].ConfigFile) {
			q = q.Arg("configFile", opts[i].ConfigFile)
		}
		// `outputFile` optional argument
		if !querybuilder.IsZeroValue(opts[i].OutputFile) {
			q = q.Arg("outputFile", opts[i].OutputFile)
		}
	}

	return &File{
		query: q,
	}
}

// Push helm chart on registry (OCI format only)
// It will return the updated Chart.yaml file with the expected version
func (r *Helm) Push(registryUrl string, repositoryName string, version string) *File { // helm (https://github.com/disaster37/dagger-library-go/tree/b753e824a9c4beec16d624fb1b7f59b073934c78/helm/push.go#L15)
	q := r.query.Select("push")
	q = q.Arg("registryUrl", registryUrl)
	q = q.Arg("repositoryName", repositoryName)
	q = q.Arg("version", version)

	return &File{
		query: q,
	}
}

// Update Chart.yaml file
func (r *Helm) UpdateChart(key string, value string) *File { // helm (https://github.com/disaster37/dagger-library-go/tree/b753e824a9c4beec16d624fb1b7f59b073934c78/helm/update.go#L10)
	q := r.query.Select("updateChart")
	q = q.Arg("key", key)
	q = q.Arg("value", value)

	return &File{
		query: q,
	}
}

// Update values.yaml file
func (r *Helm) UpdateValues(key string, value string) *File { // helm (https://github.com/disaster37/dagger-library-go/tree/b753e824a9c4beec16d624fb1b7f59b073934c78/helm/update.go#L30)
	q := r.query.Select("updateValues")
	q = q.Arg("key", key)
	q = q.Arg("value", value)

	return &File{
		query: q,
	}
}

// HelmWithRepositoryOpts contains options for Helm.WithRepository
type HelmWithRepositoryOpts struct {
	//
	// The repository name
	// You need to set it when is not OCI format
	//
	Name string // helm (https://github.com/disaster37/dagger-library-go/tree/b753e824a9c4beec16d624fb1b7f59b073934c78/helm/main.go#L95)
	//
	// Is it an OCI repository
	//
	IsOci bool // helm (https://github.com/disaster37/dagger-library-go/tree/b753e824a9c4beec16d624fb1b7f59b073934c78/helm/main.go#L103)
}

// WithRepository permit to login on private helm repository
func (r *Helm) WithRepository(url string, username *Secret, password *Secret, opts ...HelmWithRepositoryOpts) *Helm { // helm (https://github.com/disaster37/dagger-library-go/tree/b753e824a9c4beec16d624fb1b7f59b073934c78/helm/main.go#L89)
	assertNotNil("username", username)
	assertNotNil("password", password)
	q := r.query.Select("withRepository")
	for i := len(opts) - 1; i >= 0; i-- {
		// `name` optional argument
		if !querybuilder.IsZeroValue(opts[i].Name) {
			q = q.Arg("name", opts[i].Name)
		}
		// `isOci` optional argument
		if !querybuilder.IsZeroValue(opts[i].IsOci) {
			q = q.Arg("isOci", opts[i].IsOci)
		}
	}
	q = q.Arg("url", url)
	q = q.Arg("username", username)
	q = q.Arg("password", password)

	return &Helm{
		query: q,
	}
}

// WithSource permit to update the current source
func (r *Helm) WithSource(src *Directory) *Helm { // helm (https://github.com/disaster37/dagger-library-go/tree/b753e824a9c4beec16d624fb1b7f59b073934c78/helm/main.go#L136)
	assertNotNil("src", src)
	q := r.query.Select("withSource")
	q = q.Arg("src", src)

	return &Helm{
		query: q,
	}
}

// WithWorkDir change the working directory on all containers
func (r *Helm) WithWorkDir(path string) *Helm { // helm (https://github.com/disaster37/dagger-library-go/tree/b753e824a9c4beec16d624fb1b7f59b073934c78/helm/main.go#L152)
	q := r.query.Select("withWorkDir")
	q = q.Arg("path", path)

	return &Helm{
		query: q,
	}
}

func (r *Helm) YqContainer() *Container { // helm (https://github.com/disaster37/dagger-library-go/tree/b753e824a9c4beec16d624fb1b7f59b073934c78/helm/main.go#L34)
	q := r.query.Select("yqContainer")

	return &Container{
		query: q,
	}
}

// AsNode returns this Helm as a Node.
// This is a local type conversion — no GraphQL call.
func (r *Helm) AsNode() Node {
	return &NodeClient{
		query: r.query,
	}
}

// HelmOpts contains options for Query.Helm
type HelmOpts struct {
	//
	// base helm container
	// It need contain helm
	//
	BaseHelmContainer *Container // helm (https://github.com/disaster37/dagger-library-go/tree/b753e824a9c4beec16d624fb1b7f59b073934c78/helm/main.go#L45)
	//
	// Base generator container
	// It need contain readme-generator-for-helm
	//
	BaseGeneratorContainer *Container // helm (https://github.com/disaster37/dagger-library-go/tree/b753e824a9c4beec16d624fb1b7f59b073934c78/helm/main.go#L50)
	//
	// Base YQ container
	// It need contain yq
	//
	BaseYqContainer *Container // helm (https://github.com/disaster37/dagger-library-go/tree/b753e824a9c4beec16d624fb1b7f59b073934c78/helm/main.go#L55)
}

// A generated module for Helm functions
//
// This module has been generated via dagger init and serves as a reference to
// basic module structure as you get started with Dagger.
//
// Two functions have been pre-created. You can modify, delete, or add to them,
// as needed. They demonstrate usage of arguments and return types using simple
// echo and grep commands. The functions can be called from the dagger CLI or
// from one of the SDKs.
//
// The first line in this comment block is a short description line and the
// rest is a long description with more detail on the module's purpose or usage,
// if appropriate. All modules should have a short description.
func (r *Query) Helm(src *Directory, opts ...HelmOpts) *Helm { // helm (https://github.com/disaster37/dagger-library-go/tree/b753e824a9c4beec16d624fb1b7f59b073934c78/helm/main.go#L37)
	assertNotNil("src", src)
	q := r.query.Select("helm")
	for i := len(opts) - 1; i >= 0; i-- {
		// `baseHelmContainer` optional argument
		if !querybuilder.IsZeroValue(opts[i].BaseHelmContainer) {
			q = q.Arg("baseHelmContainer", opts[i].BaseHelmContainer)
		}
		// `baseGeneratorContainer` optional argument
		if !querybuilder.IsZeroValue(opts[i].BaseGeneratorContainer) {
			q = q.Arg("baseGeneratorContainer", opts[i].BaseGeneratorContainer)
		}
		// `baseYqContainer` optional argument
		if !querybuilder.IsZeroValue(opts[i].BaseYqContainer) {
			q = q.Arg("baseYqContainer", opts[i].BaseYqContainer)
		}
	}
	q = q.Arg("src", src)

	return &Helm{
		query: q,
	}
}
