{{- if .Values.tools.grafana.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "dagger-kubernetes.fullname" . }}-grafana-datasources
  namespace: {{ include "dagger-kubernetes.namespace" . }}
  labels:
    {{- include "dagger-kubernetes.labels" . | nindent 4 }}
    grafana_datasource: "1"
data:
  datasources.yaml: |
    apiVersion: 1
    datasources:
      - name: Tempo
        type: tempo
        url: "http://{{ .Release.Name }}-tempo:3200"
        access: proxy
        jsonData:
          tracesToLogsV2:
            datasourceUid: loki
            spanStartTimeShift: "-1h"
            spanEndTimeShift: "1h"
            filterByTraceID: true
            filterBySpanID: true
            tags: [{ key: "service.name", value: "job" }]
      - name: Loki
        type: loki
        url: "http://{{ .Release.Name }}-loki:3100"
        access: proxy
      - name: VictoriaMetrics
        type: prometheus
        url: "http://{{ .Release.Name }}-victoria-server:8428"
        access: proxy
        isDefault: true
        jsonData:
          timeInterval: "15s"
        editable: true
{{- end }}
