{{- if .Values.auth.tokens }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "dagger-kubernetes.fullname" . }}-tokens
  namespace: {{ include "dagger-kubernetes.namespace" . }}
  labels:
    {{- include "dagger-kubernetes.labels" . | nindent 4 }}
type: Opaque
stringData:
  tokens: |-
{{- range .Values.auth.tokens }}
    {{ . }}
{{- end }}
{{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "dagger-kubernetes.fullname" . }}-minting-ca
  namespace: {{ include "dagger-kubernetes.namespace" . }}
  labels:
    {{- include "dagger-kubernetes.labels" . | nindent 4 }}
type: Opaque
{{- with .Values.ca }}
stringData:
  ca.crt: {{ .crt | quote }}
  ca.key: {{ .key | quote }}
{{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "dagger-kubernetes.fullname" . }}-tls
  namespace: {{ include "dagger-kubernetes.namespace" . }}
  labels:
    {{- include "dagger-kubernetes.labels" . | nindent 4 }}
type: kubernetes.io/tls
{{- with .Values.tls }}
data:
  tls.crt: {{ .crt | b64enc | quote }}
  tls.key: {{ .key | b64enc | quote }}
{{- end }}
