apiVersion: v1
kind: Service
metadata:
  name: {{ include "dagger-kubernetes.fullname" . }}-control
  namespace: {{ include "dagger-kubernetes.namespace" . }}
  labels:
    {{- include "dagger-kubernetes.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.control.type }}
  selector:
    {{- include "dagger-kubernetes.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.control.port }}
      targetPort: control
      {{- if and (eq .Values.service.control.type "NodePort") .Values.service.control.nodePort }}
      nodePort: {{ .Values.service.control.nodePort }}
      {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "dagger-kubernetes.fullname" . }}-data
  namespace: {{ include "dagger-kubernetes.namespace" . }}
  labels:
    {{- include "dagger-kubernetes.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.data.type }}
  selector:
    {{- include "dagger-kubernetes.selectorLabels" . | nindent 4 }}
  ports:
    - name: tls
      port: {{ .Values.service.data.port }}
      targetPort: data
