name: release
"on":
  release:
    types:
      - created
jobs:
  publish-docker:
    permissions:
      contents: write
      packages: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository }}:${{ github.ref_name }}
  publish-helm:
    permissions:
      contents: write
      packages: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Publish Helm Chart
        run: |
          VERSION="${{ github.ref_name }}"
          REPO="${{ github.repository_owner }}"
          echo "${{ secrets.GITHUB_TOKEN }}" | helm registry login ghcr.io \
            --username "${{ github.actor }}" \
            --password-stdin
          helm dependency update deploy/helm/dagger-kubernetes
          helm package deploy/helm/dagger-kubernetes --version "${VERSION#v}" --app-version "${VERSION#v}"
          helm push dagger-kubernetes-${VERSION#v}.tgz oci://ghcr.io/${REPO}/charts
